# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry_game', '0003_auto_20171219_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='driving_forward',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='driving_loaded_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='driving_loaded_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='driving_unloaded_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='driving_unloaded_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='fuel_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='idling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='loading_and_unloading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='loads_transported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='logs_deposited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='productivity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='reverse',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='worker_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
